### PR TITLE
`#[zeroize(drop)]` is deprecated in `zeroize`

### PR DESCRIPTION
**Pull request by weikengchen**
This PR is to fix the compilation errors on nightly because `#[zeroize(drop)]` is no longer supported with newer versions of `zeroize`. It is now replaced by another trait `ZeroizeOnDrop`.

One question: what is the MSVC plan for merlin?

### CODE REVIEW

**Comment by weikengchen** [comment]
I would like to cc @tarcieri on this.

**Comment by tarcieri** [comment]
`#[zeroize(drop)]` is still "supported" but deprecated.

`ZeroizeOnDrop` is preferred as of 1.5, however you'll need to use that as the minimum `zeroize` version for this to always work.

**Comment by weikengchen** [comment]
Let me dig a little bit about why it does not work in one of our codebases...

**Comment by weikengchen** [comment]
OK. I think the error was 3 days ago because it uses the yanked version of zeroize_derive.

Let me close this PR for now.

**Comment by weikengchen** [comment]
Really sorry. It is a false alarm.

**Pull request closed without merging**
